services:
  ocbot:
    image: ghcr.io/openclaw/openclaw:latest
    restart: unless-stopped
    environment:
      - HOME=/home/node
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_OWNER_ID=${TELEGRAM_OWNER_ID}
      - OPENCLAW_CONFIG_PATH=/home/node/.openclaw/openclaw.json
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        curl -fsSL https://raw.githubusercontent.com/ioleksiy/openclaw-docker-stack/refs/heads/main/assets/openclaw-original.json \
          | envsubst > /home/node/.openclaw/openclaw.json
        exec node dist/index.js gateway --bind lan --port 18789
    volumes:
      - oc-config:/home/node/.openclaw
      - oc-workspace:/home/node/.openclaw/workspace
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  oc-config:
  oc-workspace:
